---
title: "portfolio-optimisation"
author: "Jeremy Forbes"
date: "04/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Useful packages

```{r, echo=FALSE, include=FALSE}
library(tidyquant)
library(tidyverse)
source("stonks_app/functions.R")
```

## Load portfolio

Currently I have:
- NDQ.AX
- A200.AX
- ASIA.AX

```{r}
tickers = c(
  'NAB.AX'
  , 'ANZ.AX'
  # 'NDQ.AX'
  # , 'A200.AX'
  # , 'ASIA.AX'
  # , 'MOAT.AX'
  # , 'F100.AX'
  # , 'HACK.AX'
  # , 'GGUS.AX'
  # , 'ETPMPD.AX'
  # , 'QRE.AX'
  # , 'MVR.AX'
  # , 'MVE.AX'
  ) %>%
  sort()
```

Get daily prices

```{r}
# Daily prices
prices_df <- get_prices_for_all_tickers(tickers)
```

Get daily returns

```{r}
# Daily returns
daily_returns <- daily_returns(prices_df)
```

Compute mean returns and covariance matrix

```{r}
mean_rtrn <- mean_returns(daily_returns)
cov_rtrn <- cov_returns(daily_returns)

mean_rtrn
cov_rtrn
```



## Global minimum variance

```{r}
one_vec = rep(1, length(tickers))
cov_rtrn_inv = solve(cov_rtrn)
top.mat = cov_rtrn_inv%*%one_vec
bot.val = as.numeric((t(one_vec)%*%cov_rtrn_inv%*%one_vec))
min_var_split = top.mat/bot.val

# Print minmum variance portfolio
mvp = min_var_split[,1]
mvp

# Annual return
mvp_return = (mvp%*%mean_rtrn)[1,1]
mvp_return

# Annual risk
mvp_variance = as.numeric(t(mvp) %*% cov_rtrn %*% mvp)
mvp_sigma = mvp_variance %>% sqrt()
mvp_sigma
```


## Global maximum sharpe ratio

```{r}
rf = 0
mean_rtrn_less_rf = mean_rtrn - rf
one_vec = rep(1, length(tickers))
cov_rtrn_inv = solve(cov_rtrn)
top.mat = cov_rtrn_inv%*%mean_rtrn_less_rf
bot.val = as.numeric(t(one_vec)%*%top.mat)
op = top.mat[,1]/bot.val

# Optimal portfolio
op

# Annual return
op_return = (op%*%mean_rtrn)[1,1]
op_return

# Annual risk
op_variance = as.numeric(t(op) %*% cov_rtrn %*% op)
op_sigma = op_variance %>% sqrt()
op_sigma
```


## Random portfolio splits

```{r}
random_splits <- function(tickers, n=100) {
  random_wts <- matrix(runif(n*length(tickers)), ncol=length(tickers))
  colnames(random_wts) = tickers
  standardised_wts <- random_wts / rowSums(random_wts)
  rounded_wts <- round(standardised_wts, 2)
  
  # Discard any that don't add to 1 exactly
  out <- rounded_wts[rowSums(rounded_wts) == 1,] %>% 
    unique()
  
  return(out)
}
```


```{r}
candidate_wts = random_splits(tickers, n=100)
candidate_wts %>% dim
```

## Calculate returns and risk

```{r}
# Annual returns
port_returns <- (candidate_wts %*% mean_daily_returns + 1)^252 - 1
```

```{r}
# Annual risk
compute_risk <- function(cov_returns, wts) {
  return(sqrt(t(wts) %*% (cov_returns %*% wts)))
}

port_risk <- candidate_wts %>% apply(1,compute_risk, cov_returns=cov_rtrn)
```

```{r}
cov_rtrn
x = c(0.5, 0.5)
x
```

```{r}
compute_risk(cov_rtrn, x)
```

```{r}
# Combine into data frame
df <- data_frame(
  return = port_returns %>% as.vector(),
  risk = port_risk %>% as.vector()
) %>% 
  mutate(sharpe_ratio = return/risk) %>% 
  bind_cols(candidate_wts %>% as.data.frame())
```

```{r}
# Maximum sharpe ratio
df %>% 
  arrange(desc(sharpe_ratio)) %>% 
  head()
```


```{r}
# Minimum risk
df %>% 
  arrange(risk) %>% 
  head()
```


## Take the best 100 portfolio options, and average the splits for each share

```{r}
df %>% 
  arrange(desc(sharpe_ratio)) %>% 
  head(100) %>% 
  colMeans() %>% 
  round(2)
```



## Plot

```{r}
df %>% 
  ggplot(aes(x=risk, y=return, col=sharpe_ratio)) +
  geom_point(size=0.25) +
  scale_color_gradient(low = 'purple', high = 'orange')
```


